apiVersion: apps/v1
kind: Deployment
metadata:
  name: visdom
spec:
  selector:
    matchLabels:
      app: visdom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: visdom
    spec:
      containers:
      - name: visdom
        image: "anibali/visdom:0.1.8.5"
        ports:
        - containerPort: 8097
          name: visdom
---
apiVersion: v1
kind: Service
metadata:
  name: visdom
  labels:
    app: visdom
spec:
  type: ClusterIP
  ports:
    - port: 8097
      protocol: TCP
      name: visdom
      targetPort: 8097
  selector:
    app: visdom
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: visdom
  labels:
    app: visdom
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: visdom.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: visdom
              servicePort: 8097
  tls:
    - hosts: [visdom.example.com]
